### ISSUE TITLE
Adding a mixin module and drop silent class

### ISSUE THREAD

**Issue by csshugs** [inuitcss/objects.list-bare#1]
As discussed [here](https://github.com/inuitcss/CONTRIBUTING/issues/18#issuecomment-98657159), providing a mixin will avoid encouraging to use `@extend`:

``` scss
// _tools.list-bare.scss
@mixin inuit-list-bare() {
    margin:  0;
    padding: 0;
    list-style: none;
}
```

...and you can still use the class in the markup:

``` scss
// _objects.list-bare.scss
.#{$inuit-list-bare-namespace}o-list-bare {
    @include inuit-list-bare();
}
```

So this:

``` html
<ul class="site-nav  o-list-bare">
    ...
</ul>
```

is as possible as this:

``` html
<ul class="site-nav">
    ...
</ul>

.site-nav {
    @include inuit-list-bare();
}
```
